name: KillEffect
main: MCPH\KillEffect\Main
version: 1.1beta.1
api: 1.13.0
dependent: EconomyAPI
load: STARTUP
author: MinecrafterPH
description: Get effects when killing someone.
website: http://www.minecrafterph.tk
